-- Expand ActivityAction enum with fine-grained event types for event sourcing.
-- PostgreSQL requires enum additions outside a transaction.
ALTER TYPE "ActivityAction" ADD VALUE IF NOT EXISTS 'TITLE_CHANGED';
ALTER TYPE "ActivityAction" ADD VALUE IF NOT EXISTS 'PRIORITY_CHANGED';
ALTER TYPE "ActivityAction" ADD VALUE IF NOT EXISTS 'DESCRIPTION_CHANGED';
ALTER TYPE "ActivityAction" ADD VALUE IF NOT EXISTS 'STORY_POINTS_CHANGED';
ALTER TYPE "ActivityAction" ADD VALUE IF NOT EXISTS 'ESTIMATED_TIME_CHANGED';
ALTER TYPE "ActivityAction" ADD VALUE IF NOT EXISTS 'SPRINT_CHANGED';
ALTER TYPE "ActivityAction" ADD VALUE IF NOT EXISTS 'PROJECT_CHANGED';
ALTER TYPE "ActivityAction" ADD VALUE IF NOT EXISTS 'LABELS_CHANGED';
ALTER TYPE "ActivityAction" ADD VALUE IF NOT EXISTS 'MODULE_CHANGED';
ALTER TYPE "ActivityAction" ADD VALUE IF NOT EXISTS 'CO_ASSIGNEE_ADDED';
ALTER TYPE "ActivityAction" ADD VALUE IF NOT EXISTS 'CO_ASSIGNEE_REMOVED';
